export default {
  firstRow: [
    { label: "3", color: "red" },
    { label: "6", color: "black" },
    { label: "9", color: "red" },
    { label: "12", color: "red" },
    { label: "15", color: "black" },
    { label: "18", color: "red" },
    { label: "21", color: "red" },
    { label: "24", color: "black" },
    { label: "27", color: "red" },
    { label: "30", color: "red" },
    { label: "33", color: "black" },
    { label: "36", color: "red" },
  ],
  secondRow: [
    { label: "2", color: "black" },
    { label: "5", color: "red" },
    { label: "8", color: "black" },
    { label: "11", color: "black" },
    { label: "14", color: "red" },
    { label: "17", color: "black" },
    { label: "20", color: "black" },
    { label: "23", color: "red" },
    { label: "26", color: "black" },
    { label: "29", color: "black" },
    { label: "32", color: "red" },
    { label: "35", color: "black" },
  ],
  thirdRow: [
    { label: "1", color: "red" },
    { label: "4", color: "black" },
    { label: "7", color: "red" },
    { label: "10", color: "red" },
    { label: "13", color: "black" },
    { label: "16", color: "red" },
    { label: "19", color: "red" },
    { label: "22", color: "black" },
    { label: "25", color: "red" },
    { label: "28", color: "red" },
    { label: "31", color: "black" },
    { label: "34", color: "red" },
  ],
};
